#!/bin/bash

# Helper script to set up .env.local for local Supabase development
# Usage: ./scripts/setup-local-env.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ADMIN_DIR="$(dirname "$SCRIPT_DIR")"
SUPABASE_DIR="$(dirname "$ADMIN_DIR")/supabase"

echo "🔧 Setting up local environment for admin app..."
echo ""

# Check if supabase directory exists
if [ ! -d "$SUPABASE_DIR" ]; then
  echo "❌ Supabase directory not found at: $SUPABASE_DIR"
  exit 1
fi

# Check if local Supabase is running
cd "$SUPABASE_DIR"
if ! supabase status > /dev/null 2>&1; then
  echo "❌ Local Supabase is not running!"
  echo "   Please run: cd $SUPABASE_DIR && supabase start"
  exit 1
fi

# Get credentials using the helper script
echo "📋 Getting local Supabase credentials..."
if [ -f "scripts/get-local-credentials.sh" ]; then
  ./scripts/get-local-credentials.sh > /dev/null 2>&1
else
  echo "⚠️  Credentials script not found, trying to extract manually..."
  # Fallback: try to extract directly
  STATUS=$(supabase status 2>/dev/null)
  ANON_KEY=$(echo "$STATUS" | grep -oE 'sb_publishable_[A-Za-z0-9_-]+' | head -1)
  API_URL=$(echo "$STATUS" | grep -i "Project URL" | awk '{print $NF}' | head -1)
  if [ -z "$API_URL" ]; then
    API_URL="http://127.0.0.1:54321"
  fi
  mkdir -p .temp
  echo "$ANON_KEY" > .temp/anon-key
  echo "$API_URL" > .temp/api-url
fi

# Read credentials from .temp directory (in supabase root, not scripts)
if [ -f ".temp/anon-key" ]; then
  ANON_KEY=$(cat .temp/anon-key | tr -d '\n' | tr -d '\r')
  if [ -z "$ANON_KEY" ]; then
    echo "❌ Anon key is empty. Please run: cd $SUPABASE_DIR && ./scripts/get-local-credentials.sh"
    exit 1
  fi
else
  echo "❌ Could not find anon key. Please run: cd $SUPABASE_DIR && ./scripts/get-local-credentials.sh"
  exit 1
fi

if [ -f ".temp/api-url" ]; then
  API_URL=$(cat .temp/api-url | tr -d '\n' | tr -d '\r')
else
  API_URL="http://127.0.0.1:54321"
fi

# Create .env.local in admin directory
cd "$ADMIN_DIR"
ENV_FILE=".env.local"

echo "# Local Supabase Configuration" > "$ENV_FILE"
echo "# Auto-generated by setup-local-env.sh" >> "$ENV_FILE"
echo "# Generated at: $(date)" >> "$ENV_FILE"
echo "#" >> "$ENV_FILE"
echo "# To regenerate, run: ./scripts/setup-local-env.sh" >> "$ENV_FILE"
echo "" >> "$ENV_FILE"
echo "NEXT_PUBLIC_SUPABASE_URL=$API_URL" >> "$ENV_FILE"
echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=$ANON_KEY" >> "$ENV_FILE"

echo "✅ Created $ENV_FILE with local Supabase credentials"
echo ""
echo "📝 Configuration:"
echo "   NEXT_PUBLIC_SUPABASE_URL=$API_URL"
echo "   NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY:0:50}..."
echo ""
echo "🚀 Next steps:"
echo "   1. npm install (if not already done)"
echo "   2. npm run dev"
echo "   3. Sign in at http://localhost:3000/sign-in"
echo ""
echo "🔐 Test credentials (if database is seeded):"
echo "   Admin: admin@test.com / admin123456"
echo "   Customer: john.doe@test.com / customer123"
echo "   Laundry: mike@cleanlaundry.co.za / laundry123"
echo "   Driver: driver1@test.com / driver123"
echo ""
echo "💡 To seed the database:"
echo "   cd $SUPABASE_DIR && ./scripts/seed-all.sh"
